version: 1.1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS_VERSION: 15 2017
    VS_PLATFORM: win32
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS_VERSION: 15 2017
    VS_PLATFORM: x64

before_build:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg integrate install
  - vcpkg install brynet --head
  - vcpkg install protobuf:x86-windows
  - vcpkg install protobuf:x64-windows
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - echo Running cmake...
  - cmake -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake . -G "Visual Studio %VS_VERSION%"

build:
  project: gayrpc.sln
  parallel: true
  verbosity: minimal

test_script:
    - cd tests
    - ctest -V -C %CONFIGURATION%